import type { Plan, PublicProperty } from "./domain";
export const heroImage = "/images/tropical-home.jpg";
export const landImage = "/images/land.jpg";
export const demoAreas = [
  "Independence Layout",
  "GRA",
  "Trans Ekulu",
  "New Haven",
  "Emene",
  "Abakpa Nike",
  "Uwani",
  "Achara Layout",
  "Coal Camp",
  "Ogui",
  "Ogui Road",
  "Thinkers Corner",
  "Nike",
  "Centenary City",
  "Maryland",
  "Ugwuaji",
  "Awkunanaw",
].map((name, i) => ({
  id: `demo-area-${i}`,
  name,
  slug: name.toLowerCase().replaceAll(" ", "-"),
  kind: "area",
  description: "",
}));
export const seedPlans: Plan[] = [
  {
    id: "free",
    name: "Free",
    price_minor: 0,
    duration_days: 30,
    photo_limit: 4,
    video_limit: 0,
    featured_days: 0,
  },
  {
    id: "plus",
    name: "Plus",
    price_minor: 500000,
    duration_days: 45,
    photo_limit: 15,
    video_limit: 1,
    featured_days: 0,
  },
  {
    id: "premium",
    name: "Premium",
    price_minor: 1500000,
    duration_days: 60,
    photo_limit: 30,
    video_limit: 3,
    featured_days: 7,
  },
];
export const demoProperties: PublicProperty[] = [
  {
    id: "demo-1",
    reference: "EP-DEMO-000001",
    slug: "4-bedroom-detached-duplex-independence-layout-demo",
    title: "A considered home. Room for everything.",
    description:
      "Fictional development example: a four-bedroom detached duplex with generous living spaces, a private courtyard and room for a growing family. The photographs are illustrative stock photography and do not depict a property offered for sale in Enugu.",
    category: "houses",
    area: "Independence Layout",
    area_slug: "independence-layout",
    price_minor: 18500000000,
    bedrooms: 4,
    bathrooms: 5,
    land_sqm: 650,
    features: [
      "En-suite bedrooms",
      "Private courtyard",
      "Parking spaces",
      "Guest room",
    ],
    images: [heroImage],
    seller_type: "owner",
    status: "live",
    created_at: "2026-09-10T12:00:00Z",
    updated_at: "2026-09-10T12:00:00Z",
    featured: true,
    price_reduced: false,
    checks: [],
    demo: true,
  },
  {
    id: "demo-2",
    reference: "EP-DEMO-000002",
    slug: "residential-land-emene-demo",
    title: "Space to build your own beginning.",
    description:
      "Fictional development example: a residential plot in Emene. Buyers should establish boundaries, access, permitted use and title through appropriate inspections and professional searches. The image is an illustrative landscape, not this location.",
    category: "land",
    area: "Emene",
    area_slug: "emene",
    price_minor: 1800000000,
    bedrooms: null,
    bathrooms: null,
    land_sqm: 1000,
    features: [
      "Residential use proposed",
      "Road access to be checked",
      "Survey review available on request",
    ],
    images: [landImage],
    seller_type: "agent",
    status: "live",
    created_at: "2026-09-09T12:00:00Z",
    updated_at: "2026-09-09T12:00:00Z",
    featured: true,
    price_reduced: false,
    checks: [],
    demo: true,
  },
  {
    id: "demo-3",
    reference: "EP-DEMO-000003",
    slug: "5-bedroom-family-home-trans-ekulu-demo",
    title: "A fresh perspective on family living.",
    description:
      "Fictional development example: a spacious five-bedroom home in Trans Ekulu. Arrange an inspection to assess the condition and commission independent advice before making a purchase decision. Stock photography is for interface demonstration only.",
    category: "houses",
    area: "Trans Ekulu",
    area_slug: "trans-ekulu",
    price_minor: 12500000000,
    bedrooms: 5,
    bathrooms: 5,
    land_sqm: 720,
    features: ["Family living room", "Balcony", "Parking", "Outdoor space"],
    images: ["/images/white-home.jpg"],
    seller_type: "developer",
    status: "live",
    created_at: "2026-09-08T12:00:00Z",
    updated_at: "2026-09-08T12:00:00Z",
    featured: true,
    price_reduced: true,
    checks: [],
    demo: true,
  },
  {
    id: "demo-4",
    reference: "EP-DEMO-000004",
    slug: "development-land-ugwuaji-demo",
    title: "A larger canvas for your next project.",
    description:
      "Fictional development example: development land in Ugwuaji. All planning, boundary and access details would require confirmation before a real listing could be approved.",
    category: "land",
    area: "Ugwuaji",
    area_slug: "ugwuaji",
    price_minor: 6800000000,
    bedrooms: null,
    bathrooms: null,
    land_sqm: 2400,
    features: ["Development opportunity", "Boundary review required"],
    images: [landImage],
    seller_type: "owner",
    status: "live",
    created_at: "2026-09-07T12:00:00Z",
    updated_at: "2026-09-07T12:00:00Z",
    featured: false,
    price_reduced: false,
    checks: [],
    demo: true,
  },
];
